<?php
echo '<nav class="navbar navbar-inverse">';
echo '<div class="container-fluid">';
echo '<div class="navbar-header">';
echo '<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">';
echo '<span class="icon-bar"></span>';
echo '<span class="icon-bar"></span>';
echo '<span class="icon-bar"></span> ';
echo '</button>';
echo '<a class="navbar-brand" href="#">' . $_SESSION[APP_NAME] . '</a>';
echo '</div>';
echo '<div class="collapse navbar-collapse" id="myNavbar">';
echo '<ul class="nav navbar-nav">';
echo '<li class="active"><a href="#">Home</a></li>';
echo '<li><a href="#">Page 1</a></li>';
echo '<li><a href="#">Page 2</a></li> ';
echo '<li><a href="#">Page 3</a></li> ';
echo '</ul>';
echo '<ul class="nav navbar-nav navbar-right">';
echo '<li><a href="#">' . $_SESSION[SESSION_USER] . '</a></li>';
echo '<li><a href="logout.php"><span class="glyphicon glyphicon-log-out"></span> Salir</a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</nav>';
